autoInstallPeers: false
overrides:
  "@xmldom/xmldom@0.8.13": 0.8.15
  "@xmldom/xmldom@0.9.10": 0.9.12
  decode-uri-component: 0.5.0
  joi@17.11.0: 17.13.4
  uuid@7.0.3: 11.1.1
allowBuilds:
  dtrace-provider: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@expo/cli@57.0.14 || 57.0.15 || 57.0.21"
  - "@expo/fingerprint@0.20.7 || 0.20.12"
  - "@expo/inline-modules@0.1.5"
  - "@expo/local-build-cache-provider@57.0.6"
  - "@expo/metro-config@57.0.8"
  - "@expo/prebuild-config@57.0.11 || 57.0.12"
  - expo-asset@57.0.11 || 57.0.16
  - expo-constants@57.0.11 || 57.0.17
  - expo-server@57.0.2 || 57.0.3
  - expo@57.0.13 || 57.0.19
  - "@expo/metro-runtime@57.0.9 || 57.0.10 || 57.0.15"
  - "@expo/ui@57.0.10 || 57.0.11 || 57.0.15"
  - expo-dev-client@57.0.12 || 57.0.18
  - expo-dev-launcher@57.0.11 || 57.0.12 || 57.0.19
  - expo-dev-menu@57.0.11 || 57.0.12 || 57.0.18
  - expo-linking@57.0.6 || 57.0.9
  - expo-router@57.0.13 || 57.0.18
  - expo-splash-screen@57.0.6
  - jest-expo@57.0.4
  - "@expo/config-plugins@57.0.8"
  - "@expo/router-server@57.0.6 || 57.0.9"
  - babel-preset-expo@57.0.7 || 57.0.10
  - expo-file-system@57.0.3
  - expo-modules-autolinking@57.0.10
  - expo-modules-core@57.0.11 || 57.0.15
  - expo-font@57.0.3
  - expo-modules-jsi@57.0.7
