import type { ConsumerAudioWork } from "@/domain/audio/consumerTypes";

type Pack02WorkInput = Pick<
  ConsumerAudioWork,
  | "id"
  | "title"
  | "familyId"
  | "assetKey"
  | "sourceFilename"
  | "localPreviewFilename"
  | "primaryOutcome"
  | "secondaryOutcomes"
  | "collectionIds"
  | "durationSeconds"
  | "frameCount"
  | "measuredLufs"
  | "truePeakDbtp"
>;

function pack02Work(input: Pack02WorkInput): ConsumerAudioWork {
  return {
    schemaVersion: 1,
    ...input,
    sourceKind: "file",
    noiseColor: null,
    spectralDefinition: null,
    loop: true,
    sampleRateHz: 48000,
    channels: 2,
    bitDepth: 24,
    playbackGainDb: 0,
    postGainTruePeakDbtp: input.truePeakDbtp,
    generatedPeakCeilingDbfs: null,
    availability: "local-preview-file",
    listeningStatus: "APPROVED — LISTENING PASSED",
    provenance: {
      packId: "APP_READY_AUDIO_02_ELEMENTAL_WATER_AIR",
      manifestReference: "QA/APP_READY_AUDIO_02_MANIFEST.json",
    },
  };
}

export const APPROVED_ELEMENTAL_WORKS: readonly ConsumerAudioWork[] = [
  pack02Work({
    id: "field-rain-001-silver-canopy",
    title: "Silver Canopy",
    familyId: "field-rain-001",
    assetKey: "fieldRain001SilverCanopy",
    sourceFilename: "FIELD_RAIN_001_SILVER_CANOPY_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_001_SILVER_CANOPY_48K24_LOOP.flac",
    primaryOutcome: "focus",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 45.5,
    frameCount: 2184000,
    measuredLufs: -18,
    truePeakDbtp: -8.38,
  }),
  pack02Work({
    id: "field-rain-002-soft-weather",
    title: "Soft Weather",
    familyId: "field-rain-002",
    assetKey: "fieldRain002SoftWeather",
    sourceFilename: "FIELD_RAIN_002_SOFT_WEATHER_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_002_SOFT_WEATHER_48K24_LOOP.flac",
    primaryOutcome: "relax",
    secondaryOutcomes: ["sleep"],
    collectionIds: ["elemental-water"],
    durationSeconds: 30.5,
    frameCount: 1464000,
    measuredLufs: -22.59,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-rain-003-deep-rain",
    title: "Deep Rain",
    familyId: "field-rain-003",
    assetKey: "fieldRain003DeepRain",
    sourceFilename: "FIELD_RAIN_003_DEEP_RAIN_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_003_DEEP_RAIN_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["focus"],
    collectionIds: ["elemental-water"],
    durationSeconds: 20,
    frameCount: 960000,
    measuredLufs: -18,
    truePeakDbtp: -6.69,
  }),
  pack02Work({
    id: "field-rain-004-fine-rain",
    title: "Fine Rain",
    familyId: "field-rain-004",
    assetKey: "fieldRain004FineRain",
    sourceFilename: "FIELD_RAIN_004_FINE_RAIN_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_004_FINE_RAIN_48K24_LOOP.flac",
    primaryOutcome: "focus",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 44,
    frameCount: 2112000,
    measuredLufs: -21.41,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-rain-005-misted-garden",
    title: "Misted Garden",
    familyId: "field-rain-005",
    assetKey: "fieldRain005MistedGarden",
    sourceFilename: "FIELD_RAIN_005_MISTED_GARDEN_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_005_MISTED_GARDEN_48K24_LOOP.flac",
    primaryOutcome: "relax",
    secondaryOutcomes: ["sleep"],
    collectionIds: ["elemental-water"],
    durationSeconds: 45,
    frameCount: 2160000,
    measuredLufs: -20.8,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-rain-006-quiet-weather",
    title: "Quiet Weather",
    familyId: "field-rain-006",
    assetKey: "fieldRain006QuietWeather",
    sourceFilename: "FIELD_RAIN_006_QUIET_WEATHER_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_006_QUIET_WEATHER_48K24_LOOP.flac",
    primaryOutcome: "relax",
    secondaryOutcomes: ["sleep"],
    collectionIds: ["elemental-water"],
    durationSeconds: 20.5,
    frameCount: 984000,
    measuredLufs: -18,
    truePeakDbtp: -4.07,
  }),
  pack02Work({
    id: "field-rain-007-rain-veil",
    title: "Rain Veil",
    familyId: "field-rain-007",
    assetKey: "fieldRain007RainVeil",
    sourceFilename: "FIELD_RAIN_007_RAIN_VEIL_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_007_RAIN_VEIL_48K24_LOOP.flac",
    primaryOutcome: "focus",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 44,
    frameCount: 2112000,
    measuredLufs: -18,
    truePeakDbtp: -1.23,
  }),
  pack02Work({
    id: "field-rain-008-sheltered-rain",
    title: "Sheltered Rain",
    familyId: "field-rain-008",
    assetKey: "fieldRain008ShelteredRain",
    sourceFilename: "FIELD_RAIN_008_SHELTERED_RAIN_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_008_SHELTERED_RAIN_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 22,
    frameCount: 1056000,
    measuredLufs: -18.01,
    truePeakDbtp: -4.46,
  }),
  pack02Work({
    id: "field-rain-009-distant-shower",
    title: "Distant Shower",
    familyId: "field-rain-009",
    assetKey: "fieldRain009DistantShower",
    sourceFilename: "FIELD_RAIN_009_DISTANT_SHOWER_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_009_DISTANT_SHOWER_48K24_LOOP.flac",
    primaryOutcome: "focus",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 43,
    frameCount: 2064000,
    measuredLufs: -21.17,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-rain-010-low-rain",
    title: "Low Rain",
    familyId: "field-rain-010",
    assetKey: "fieldRain010LowRain",
    sourceFilename: "FIELD_RAIN_010_LOW_RAIN_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_010_LOW_RAIN_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 15,
    frameCount: 720000,
    measuredLufs: -18,
    truePeakDbtp: -2.5,
  }),
  pack02Work({
    id: "field-rain-011-rain-receding",
    title: "Rain Receding",
    familyId: "field-rain-011",
    assetKey: "fieldRain011RainReceding",
    sourceFilename: "FIELD_RAIN_011_RAIN_RECEDING_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_RAIN_011_RAIN_RECEDING_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 24,
    frameCount: 1152000,
    measuredLufs: -20.49,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-stream-001-stone-current",
    title: "Stone Current",
    familyId: "field-stream-001",
    assetKey: "fieldStream001StoneCurrent",
    sourceFilename: "FIELD_STREAM_001_STONE_CURRENT_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_STREAM_001_STONE_CURRENT_48K24_LOOP.flac",
    primaryOutcome: "relax",
    secondaryOutcomes: ["meditation"],
    collectionIds: ["elemental-water"],
    durationSeconds: 51,
    frameCount: 2448000,
    measuredLufs: -21.07,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-stream-002-moss-current",
    title: "Moss Current",
    familyId: "field-stream-002",
    assetKey: "fieldStream002MossCurrent",
    sourceFilename: "FIELD_STREAM_002_MOSS_CURRENT_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_STREAM_002_MOSS_CURRENT_48K24_LOOP.flac",
    primaryOutcome: "relax",
    secondaryOutcomes: ["meditation"],
    collectionIds: ["elemental-water"],
    durationSeconds: 49,
    frameCount: 2352000,
    measuredLufs: -20.99,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-stream-003-hidden-water",
    title: "Hidden Water",
    familyId: "field-stream-003",
    assetKey: "fieldStream003HiddenWater",
    sourceFilename: "FIELD_STREAM_003_HIDDEN_WATER_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_STREAM_003_HIDDEN_WATER_48K24_LOOP.flac",
    primaryOutcome: "meditation",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 57,
    frameCount: 2736000,
    measuredLufs: -20.81,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-stream-004-clear-stream",
    title: "Clear Stream",
    familyId: "field-stream-004",
    assetKey: "fieldStream004ClearStream",
    sourceFilename: "FIELD_STREAM_004_CLEAR_STREAM_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_STREAM_004_CLEAR_STREAM_48K24_LOOP.flac",
    primaryOutcome: "focus",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 69,
    frameCount: 3312000,
    measuredLufs: -17.99,
    truePeakDbtp: -5.11,
  }),
  pack02Work({
    id: "field-stream-005-cedar-stream",
    title: "Cedar Stream",
    familyId: "field-stream-005",
    assetKey: "fieldStream005CedarStream",
    sourceFilename: "FIELD_STREAM_005_CEDAR_STREAM_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_STREAM_005_CEDAR_STREAM_48K24_LOOP.flac",
    primaryOutcome: "focus",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 57,
    frameCount: 2736000,
    measuredLufs: -18,
    truePeakDbtp: -5.77,
  }),
  pack02Work({
    id: "field-sea-001-tidal-breath",
    title: "Tidal Breath",
    familyId: "field-sea-001",
    assetKey: "fieldSea001TidalBreath",
    sourceFilename: "FIELD_SEA_001_TIDAL_BREATH_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_001_TIDAL_BREATH_48K24_LOOP.flac",
    primaryOutcome: "meditation",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 158,
    frameCount: 7584000,
    measuredLufs: -27.28,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-sea-002-moon-shore",
    title: "Moon Shore",
    familyId: "field-sea-002",
    assetKey: "fieldSea002MoonShore",
    sourceFilename: "FIELD_SEA_002_MOON_SHORE_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_002_MOON_SHORE_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["meditation"],
    collectionIds: ["elemental-water"],
    durationSeconds: 162,
    frameCount: 7776000,
    measuredLufs: -23.25,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-sea-003-open-tide",
    title: "Open Tide",
    familyId: "field-sea-003",
    assetKey: "fieldSea003OpenTide",
    sourceFilename: "FIELD_SEA_003_OPEN_TIDE_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_003_OPEN_TIDE_48K24_LOOP.flac",
    primaryOutcome: "meditation",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 148,
    frameCount: 7104000,
    measuredLufs: -19.9,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-sea-004-night-shore",
    title: "Night Shore",
    familyId: "field-sea-004",
    assetKey: "fieldSea004NightShore",
    sourceFilename: "FIELD_SEA_004_NIGHT_SHORE_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_004_NIGHT_SHORE_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["meditation"],
    collectionIds: ["elemental-water"],
    durationSeconds: 156,
    frameCount: 7488000,
    measuredLufs: -19.84,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-sea-005-pearl-tide",
    title: "Pearl Tide",
    familyId: "field-sea-005",
    assetKey: "fieldSea005PearlTide",
    sourceFilename: "FIELD_SEA_005_PEARL_TIDE_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_005_PEARL_TIDE_48K24_LOOP.flac",
    primaryOutcome: "meditation",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 156,
    frameCount: 7488000,
    measuredLufs: -20.48,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-sea-006-distant-surf",
    title: "Distant Surf",
    familyId: "field-sea-006",
    assetKey: "fieldSea006DistantSurf",
    sourceFilename: "FIELD_SEA_006_DISTANT_SURF_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_006_DISTANT_SURF_48K24_LOOP.flac",
    primaryOutcome: "sleep",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 103,
    frameCount: 4944000,
    measuredLufs: -22.54,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "field-sea-007-blue-interval",
    title: "Blue Interval",
    familyId: "field-sea-007",
    assetKey: "fieldSea007BlueInterval",
    sourceFilename: "FIELD_SEA_007_BLUE_INTERVAL_48K24_LOOP.wav",
    localPreviewFilename: "FIELD_SEA_007_BLUE_INTERVAL_48K24_LOOP.flac",
    primaryOutcome: "meditation",
    secondaryOutcomes: ["relax"],
    collectionIds: ["elemental-water"],
    durationSeconds: 83,
    frameCount: 3984000,
    measuredLufs: -19.94,
    truePeakDbtp: -1.05,
  }),
  pack02Work({
    id: "esoteric-air-001-second-element",
    title: "Second Element: Air",
    familyId: "esoteric-air-001",
    assetKey: "esotericAir001SecondElement",
    sourceFilename: "ESOTERIC_AIR_001_SECOND_ELEMENT_48K24_LOOP.wav",
    localPreviewFilename: "ESOTERIC_AIR_001_SECOND_ELEMENT_48K24_LOOP.flac",
    primaryOutcome: "meditation",
    secondaryOutcomes: ["relax"],
    collectionIds: ["esoteric-series"],
    durationSeconds: 104,
    frameCount: 4992000,
    measuredLufs: -18,
    truePeakDbtp: -6.71,
  }),
];
