import type { ConsumerOutcomeId } from "./productShell";
import type {
  ConsumerAudioWork,
  ConsumerCollectionId,
} from "@/domain/audio/consumerTypes";

const COMMON = {
  schemaVersion: 1 as const,
  loop: true as const,
  sampleRateHz: 48000 as const,
  channels: 2 as const,
  bitDepth: 24 as const,
  listeningStatus: "PROVISIONAL — LISTENING APPROVAL REQUIRED" as const,
  provenance: {
    packId: "APP_READY_AUDIO_01" as const,
    manifestReference: "qa/APP_READY_AUDIO_01_MANIFEST.json" as const,
  },
};

export const CONSUMER_AUDIO_WORKS: readonly ConsumerAudioWork[] = [
  work(
    "eclipse-veil",
    "Eclipse Veil",
    "eclypsis-001",
    "eclypsis001",
    "SOUNDSCAPE_ECLYPSIS_001_EMINOR_48K24_LOOP.wav",
    "meditation",
    [],
    ["cosmic-zen-ambient"],
    172.8125,
    8295000,
    -17.999,
    -5.93,
    -0.001,
    "embedded-flac",
  ),
  work(
    "stillwater-halo",
    "Stillwater Halo",
    "nirvana-waves-001",
    "nirvanaWaves001",
    "SOUNDSCAPE_NIRVANA_WAVES_001_EMINOR_48K24_LOOP.wav",
    "relax",
    [],
    ["cosmic-zen-ambient"],
    170,
    8160000,
    -18.002,
    -5.07,
    0.002,
  ),
  work(
    "mineral-drift",
    "Mineral Drift",
    "piano-massage-001",
    "pianoMassage001",
    "SOUNDSCAPE_PIANO_MASSAGE_001_48K24_LOOP.wav",
    "massage",
    [],
    ["standalone-works"],
    1180,
    56640000,
    -18.019,
    -2.66,
    0.019,
  ),
  work(
    "astral-thread",
    "Astral Thread",
    "star-generator",
    "starGenerator001",
    "SOUNDSCAPE_STAR_GENERATOR_001_EMINOR_48K24_LOOP.wav",
    "focus",
    [],
    ["cosmic-zen-ambient"],
    170,
    8160000,
    -17.999,
    -6.48,
    -0.001,
  ),
  work(
    "celestial-current",
    "Celestial Current",
    "star-generator",
    "starGenerator002",
    "SOUNDSCAPE_STAR_GENERATOR_002_EMINOR_48K24_LOOP.wav",
    "meditation",
    [],
    ["cosmic-zen-ambient"],
    170,
    8160000,
    -18,
    -6.4,
    0,
  ),
  work(
    "quiet-field",
    "Quiet Field",
    "zen-field-waves",
    "zenFieldWaves001",
    "SOUNDSCAPE_ZEN_FIELD_WAVES_001_EMINOR_48K24_LOOP.wav",
    "yoga",
    [],
    ["cosmic-zen-ambient"],
    170.007917,
    8160380,
    -17.997,
    -5.53,
    -0.003,
  ),
  work(
    "cedar-current",
    "Cedar Current",
    "zen-generator-002",
    "zenGenerator002",
    "SOUNDSCAPE_ZEN_GENERATOR_002_EMINOR_48K24_LOOP.wav",
    "yoga",
    [],
    ["cosmic-zen-ambient"],
    170,
    8160000,
    -18,
    -6.83,
    0,
  ),
  work(
    "moonlit-veil",
    "Moonlit Veil",
    "zen-dream-003",
    "zenDream003Pad",
    "SOUNDSCAPE_ZEN_DREAM_003_PAD_48K24_LOOP.wav",
    "sleep",
    [],
    ["cosmic-zen-ambient"],
    451.706667,
    21681920,
    -21.574,
    -8.86,
    3.574,
  ),
  work(
    "moonlit-keys",
    "Moonlit Keys",
    "zen-dream-003",
    "zenDream003Piano",
    "SOUNDSCAPE_ZEN_DREAM_003_PIANO_48K24_LOOP.wav",
    "massage",
    [],
    ["standalone-works"],
    451.706667,
    21681920,
    -20.687,
    -7.59,
    2.687,
  ),
  work(
    "luminous-grain",
    "Luminous Grain",
    "zen-generator-003",
    "zenGenerator003Texture",
    "SOUNDSCAPE_ZEN_GENERATOR_003_TEXTURE_CMAJ_48K24_LOOP.wav",
    "focus",
    [],
    ["cosmic-zen-ambient"],
    452,
    21696000,
    -19.485,
    -8.09,
    1.485,
  ),
  work(
    "luminous-steps",
    "Luminous Steps",
    "zen-generator-003",
    "zenGenerator003Piano",
    "SOUNDSCAPE_ZEN_GENERATOR_003_PIANO_CMAJ_48K24_LOOP.wav",
    "massage",
    [],
    ["standalone-works"],
    452,
    21696000,
    -23.178,
    -9.77,
    5.178,
  ),
  work(
    "distant-garden",
    "Distant Garden",
    "zen-generator-004",
    "zenGenerator004Pad",
    "SOUNDSCAPE_ZEN_GENERATOR_004_PAD_CMAJ_48K24_LOOP.wav",
    "meditation",
    [],
    ["cosmic-zen-ambient"],
    976.006667,
    46848320,
    -20.048,
    -7.81,
    2.048,
  ),
  work(
    "distant-bloom",
    "Distant Bloom",
    "zen-generator-004",
    "zenGenerator004Piano",
    "SOUNDSCAPE_ZEN_GENERATOR_004_PIANO_CMAJ_48K24_LOOP.wav",
    "relax",
    [],
    ["standalone-works"],
    976.006667,
    46848320,
    -21.763,
    -8.1,
    3.763,
  ),
  work(
    "aquarian-drift",
    "Aquarian Drift",
    "zen-generator-005",
    "zenGenerator005Pad",
    "SOUNDSCAPE_ZEN_GENERATOR_005_PAD_48K24_LOOP.wav",
    "meditation",
    [],
    ["cosmic-zen-ambient"],
    1199,
    57552000,
    -21.064,
    -6.95,
    3.064,
  ),
  work(
    "aquarian-echo",
    "Aquarian Echo",
    "zen-generator-005",
    "zenGenerator005Piano",
    "SOUNDSCAPE_ZEN_GENERATOR_005_PIANO_48K24_LOOP.wav",
    "massage",
    [],
    ["standalone-works"],
    1199,
    57552000,
    -20.329,
    -5.33,
    2.329,
  ),
  work(
    "moon-drone",
    "Moon Drone",
    "audio-test-pack-01",
    "sleepDrone001",
    "SLEEP_DRONE_001.wav",
    "sleep",
    [],
    ["cosmic-zen-ambient"],
    180,
    8640000,
    -14,
    -2.02,
    -4,
    "embedded-wav",
  ),
  work(
    "deep-river",
    "Deep River",
    "audio-test-pack-01",
    "sleepAmbience001",
    "SLEEP_AMBIENCE_001.wav",
    "relax",
    ["sleep"],
    ["elemental-water"],
    180,
    8640000,
    -20.028,
    -8.01,
    2.028,
    "embedded-wav",
  ),
  work(
    "soft-air",
    "Soft Air",
    "audio-test-pack-01",
    "sleepTexture001",
    "SLEEP_TEXTURE_001.wav",
    "focus",
    ["relax"],
    ["elemental-air"],
    180,
    8640000,
    -13.999,
    -2.02,
    -4.001,
    "embedded-wav",
  ),
] as const;

function work(
  id: string,
  title: string,
  familyId: string,
  assetKey: string,
  sourceFilename: string,
  primaryOutcome: ConsumerOutcomeId,
  secondaryOutcomes: readonly ConsumerOutcomeId[],
  collectionIds: readonly ConsumerCollectionId[],
  durationSeconds: number,
  frameCount: number,
  measuredLufs: number,
  truePeakDbtp: number,
  playbackGainDb: number,
  availability: ConsumerAudioWork["availability"] = "external-flac-ready",
): ConsumerAudioWork {
  return {
    ...COMMON,
    id,
    title,
    familyId,
    assetKey,
    sourceFilename,
    primaryOutcome,
    secondaryOutcomes,
    collectionIds,
    durationSeconds,
    frameCount,
    measuredLufs,
    truePeakDbtp,
    playbackGainDb,
    postGainTruePeakDbtp: Number((truePeakDbtp + playbackGainDb).toFixed(3)),
    availability,
  };
}

export function getConsumerWork(
  id: string | undefined,
): ConsumerAudioWork | undefined {
  return CONSUMER_AUDIO_WORKS.find((item) => item.id === id);
}

export function isEmbeddedWork(work: ConsumerAudioWork): boolean {
  return (
    work.availability === "embedded-wav" ||
    work.availability === "embedded-flac"
  );
}

export function getWorksForOutcome(
  outcome: ConsumerOutcomeId,
): readonly ConsumerAudioWork[] {
  return CONSUMER_AUDIO_WORKS.filter(
    (work) =>
      work.primaryOutcome === outcome ||
      work.secondaryOutcomes.includes(outcome),
  );
}

export function getEmbeddedWorksForOutcome(
  outcome: ConsumerOutcomeId,
): readonly ConsumerAudioWork[] {
  return getWorksForOutcome(outcome).filter(isEmbeddedWork);
}

export function getWorksForCollection(
  collectionId: ConsumerCollectionId,
): readonly ConsumerAudioWork[] {
  return CONSUMER_AUDIO_WORKS.filter((work) =>
    work.collectionIds.includes(collectionId),
  );
}
